// Resource Groups
// This module deploys a Resource Group.
// https://github.com/Azure/bicep-registry-modules/tree/main/avm/res/resources/resource-group
using 'br/public:avm/res/resources/resource-group:0.4.0'

// azi autogenerated placeholders for required parameters from resources/resource-group/main.json
// Required. The name of the Resource Group.
param name = 'ocp-bm-rg'
